### PR TITLE
Backend development environment setup

### PR DESCRIPTION
**Pull request by swjeong0825**
1. Express.Ts backend environment
2. Prisma ORM
3. Error Handling

### CODE REVIEW

**Review by dima618 — COMMENTED** [review]
What is the .DS_Store file for? Is it necessary to have in the repo?

**Comment by dima618** [comment]
Also, what are the prisma migrations for? Could we change the name of the folders where the SQL files are stored to something that makes a little more sense?

**Comment by swjeong0825** [comment]
> h



> What is the .DS_Store file for? Is it necessary to have in the repo?

**Comment by swjeong0825** [comment]
> Also, what are the prisma migrations for? Could we change the name of the folders where the SQL files are stored to something more human-readable, or are they named like that for a reason?

I think the SQL files are human-readable even though it is auto-generated by the Prisma. It is sth that is auto-generated when the Prisma schema is migrated into the schema of the Postgre Database by running the command "npx prisma migrate dev --name init". I can make a new PR without this folder, but it will be created anyway locally.

**Comment by swjeong0825** [comment]
> What is the .DS_Store file for? Is it necessary to have in the repo?

I have no idea... it is not in my local dev environment lol. I'll make a new push again to remove it.

**Pull request closed without merging**
